apiVersion: v1
kind: PersistentVolume
metadata:
  name: flyway-pv
  labels:
    type: local
    app: flyway-pv
spec:
  storageClassName: manual
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: my-routine/my-storage/server-files/migration