version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: meu-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: my-storage
    volumes:
      - my-storage-data:/var/lib/postgresql/data

volumes:
  my-storage-data: