apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres-service
spec:
  ports:
    - protocol: TCP
      name: postgres-service
      port: 5432
  selector:
    app: postgres