apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flyway-pvc
  labels:
    app: flyway-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi