apiVersion: v1
kind: PersistentVolume
metadata:
  name: flyway-pv
  labels:
    type: local
    app: flyway-pv
spec:
  storageClassName: manual
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: C:\Users\Gustavo\Projects\my-routine\my-storage\migrations\src\main\resources\migration\