server:
  servlet:
    context-path: /my-storage
  port: 8081
spring:
  messages:
    basename: messages
    encoding: UTF-8
  datasource:
    url: jdbc:postgresql://localhost:5432/my-storage
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    url: jdbc:postgresql://localhost:5432/my-storage
    user: root
    password: root
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
openapi:
  service:
    title: MyStorage API
    version: 1.0.0
    url: http://localhost:8080
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html