apiVersion: v1
kind: Service
metadata:
  name: my-storage-service
spec:
  type: NodePort
  selector:
    app: my-storage
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100