name: Build and Publish

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Build Docker image
        run: docker build -t my-storage-image .

  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Log into GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u "${{ github.actor }}" --password-stdin

      - name: Tag Docker image
        run: docker tag your-docker-image docker.pkg.github.com/Narvane/my-storage/my-storage-image:${{ github.event.release.tag_name }}

      - name: Push Docker image to GitHub Packages
        run: docker push docker.pkg.github.com/Narvane/my-storag/my-storage-image:${{ github.event.release.tag_name }}